// The registry interfaces and the engine live in `@threepipe/plugin-editor-engine`; re-exported so an
// app that only installs the shell sees the same names it did before the engine became its own package.
export * from '@threepipe/plugin-editor-engine'
export {EditorViewportPlugin} from './EditorViewportPlugin'
export type {ViewportShading, AxisView, EditorViewportPluginEventMap} from './EditorViewportPlugin'
export {createModellingEditor} from './createModellingEditor'
export type {ModellingEditor, ModellingEditorOptions} from './createModellingEditor'
export {registerViewOperators} from './ops/viewOps'
export {ModellingEditorApp} from './ui/ModellingEditorApp'
export type {ModellingEditorAppProps} from './ui/ModellingEditorApp'
export {EditorUiPlugin, UiConfigRendererHeadless} from './ui/EditorUiPlugin'
export {EditorProvider, useEditor, useEngine, useEngineEvent, useEngineVersion, formatShortcut} from './ui/EditorContext'
export type {EditorContextValue} from './ui/EditorContext'
export {ContextMenuProvider, useContextMenu, operatorsToMenuItems, renderMenuItems} from './ui/ContextMenuProvider'
export type {MenuItem2} from './ui/ContextMenuProvider'
export {IconButton, PanelFlap, TooltipContent} from './ui/IconButton'
export {WindowPanesLayout} from './ui/WindowPanesLayout'
export {Header, AppMenu, ModeSwitch, SelectModeButtons, HeaderSlots} from './ui/Header'
export {Toolbar} from './ui/Toolbar'
export {Viewport} from './ui/Viewport'
export {Outliner, HierarchyTree} from './ui/Outliner'
export {Properties} from './ui/Properties'
export {PropsForm} from './ui/PropsForm'
export {OperatorPanel} from './ui/OperatorPanel'
export {StatusBar} from './ui/StatusBar'
export {CommandPalette} from './ui/CommandPalette'
export {HistoryDialog, ShortcutsDialog, AboutDialog} from './ui/Dialogs'
export {BPTreeComponent} from './ui/tree/BPTreeComponent'
export {Tree2} from './ui/tree/Tree2'
export {TreeNode2} from './ui/tree/TreeNode2'
export type {TreeNodeInfo, TreeEventHandler} from './ui/tree/treeTypes'
