import {describe, expect, it} from 'vitest'
import {
    mat4Compose,
    mat4Multiply,
    mat4RotationAxis,
    mat4RotationBetween,
    mat4RotationEuler,
    mat4TransformPoint,
    mat4Translation,
    v3cross,
    v3dot,
    v3normalize,
    Vec3,
} from './index'

/**
 * Reference values come from three.js itself, generated by `tests/gen-math-fixtures.mjs`. The kernel
 * cannot import three (see `bake.test.ts`), so the numbers are baked in rather than compared live -
 * same arrangement as the Blender parity fixtures.
 */
const ref = {
    rotationEulerXYZ: [
        0.671212166159, 0.507081872754, 0.540686787636, 0,
        -0.565354208381, 0.821954369504, -0.069033568058, 0,
        -0.479425538604, -0.259343380052, 0.838386643594, 0,
        0, 0, 0, 1,
    ],
    rotationAxis: [
        0.505911386395, -0.026896246288, -0.862166028704, 0,
        0.340787836108, 0.924433506155, 0.171132531857, 0,
        0.792412342077, -0.380393591737, 0.476847350301, 0,
        0, 0, 0, 1,
    ],
    compose: [
        1.342424332318, 1.014163745509, 1.081373575272, 0,
        -0.282677104191, 0.410977184752, -0.034516784029, 0,
        -0.719138307906, -0.389015070078, 1.257579965391, 0,
        1, -2, 3, 1,
    ],
    multiply: [
        0.671212166159, 0.507081872754, 0.540686787636, 0,
        -0.565354208381, 0.821954369504, -0.069033568058, 0,
        -0.479425538604, -0.259343380052, 0.838386643594, 0,
        0.363643967109, -1.914857006411, 3.193913854534, 1,
    ],
    transformPoint: [0.07833648819, -3.060044798695, 6.617919484422],
    rotationBetween: [
        0.251074335535, 0.852534509189, 0.458417482953, 0,
        -0.542334546402, -0.268376895253, 0.796145138698, 0,
        0.801769865868, -0.448507249368, 0.394976365685, 0,
        0, 0, 0, 1,
    ],
    rotationBetweenOpposed: [-1, 0, 0, 0, 0, -1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1],
}

const close = (a: number[], b: number[], tol = 1e-9) => {
    expect(a.length).toBe(b.length)
    for (let i = 0; i < a.length; i++) expect(a[i]).toBeCloseTo(b[i], Math.round(-Math.log10(tol)))
}

describe('math, against three.js', () => {
    it('matches makeRotationFromEuler (XYZ)', () => {
        close(mat4RotationEuler([0.3, -0.5, 0.7]), ref.rotationEulerXYZ)
    })

    it('matches makeRotationAxis', () => {
        close(mat4RotationAxis([0.3, 0.9, -0.2], 1.1), ref.rotationAxis)
    })

    it('matches compose', () => {
        close(mat4Compose([1, -2, 3], [0.3, -0.5, 0.7], [2, 0.5, 1.5]), ref.compose)
    })

    it('matches multiplyMatrices', () => {
        close(mat4Multiply(mat4RotationEuler([0.3, -0.5, 0.7]), mat4Translation([1, -2, 3])),
            ref.multiply)
    })

    it('matches Vector3.applyMatrix4', () => {
        close(mat4TransformPoint(mat4Compose([1, -2, 3], [0.3, -0.5, 0.7], [2, 0.5, 1.5]),
            [0.4, -1.2, 2.5]), ref.transformPoint)
    })

    it('matches setFromUnitVectors', () => {
        close(mat4RotationBetween([0.2, 0.9, -0.4], [-0.7, 0.1, 0.6]), ref.rotationBetween)
    })

    it('matches setFromUnitVectors for opposed vectors', () => {
        close(mat4RotationBetween([0, 1, 0], [0, -1, 0]), ref.rotationBetweenOpposed)
    })

    it('keeps rotation matrices orthonormal', () => {
        const m = mat4RotationEuler([0.3, -0.5, 0.7])
        const cols: Vec3[] = [[m[0], m[1], m[2]], [m[4], m[5], m[6]], [m[8], m[9], m[10]]]
        for (const c of cols) expect(Math.hypot(...c)).toBeCloseTo(1, 12)
        expect(v3dot(cols[0], cols[1])).toBeCloseTo(0, 12)
        expect(v3dot(cols[1], cols[2])).toBeCloseTo(0, 12)
        expect(v3dot(v3cross(cols[0], cols[1]), cols[2])).toBeCloseTo(1, 12)
    })

    it('normalises a zero vector to zero rather than NaN', () => {
        expect(v3normalize([0, 0, 0])).toEqual([0, 0, 0])
    })
})
