export {PerspectiveCamera2, PerspectiveCamera0} from './camera/PerspectiveCamera2'
export {OrthographicCamera2, OrthographicCamera0} from './camera/OrthographicCamera2'
export {CameraView, createCameraPath, type ICameraView, type CameraViewEventMap} from './camera/CameraView'
export {ExtendedShaderMaterial} from './material/ExtendedShaderMaterial'
export {PhysicalMaterial, MeshStandardMaterial2} from './material/PhysicalMaterial'
export {ShaderMaterial2} from './material/ShaderMaterial2'
export {ObjectShaderMaterial} from './material/ObjectShaderMaterial'
export {UnlitMaterial, MeshBasicMaterial2} from './material/UnlitMaterial'
export {UnlitLineMaterial, LineBasicMaterial2} from './material/UnlitLineMaterial'
export {LineMaterial2, MeshLineMaterial} from './material/LineMaterial2'
export {LegacyPhongMaterial} from './material/LegacyPhongMaterial'
export {Object3D2} from './object/Object3D2'
export {Mesh2} from './object/Mesh2'
export {InstancedMesh2} from './object/InstancedMesh2'
export {MeshLine} from './object/MeshLine'
export {MeshLineSegments} from './object/MeshLineSegments'
export {BufferGeometry2} from './geometry/BufferGeometry2'
export {LineGeometry2} from './geometry/LineGeometry2'
export {LineSegmentsGeometry2} from './geometry/LineSegmentsGeometry2'
export {WireframeGeometry3} from './geometry/WireframeGeometry3'
export {AmbientLight2} from './light/AmbientLight2'
export {DirectionalLight2} from './light/DirectionalLight2'
export {HemisphereLight2} from './light/HemisphereLight2'
export {PointLight2} from './light/PointLight2'
export {RectAreaLight2} from './light/RectAreaLight2'
export {SpotLight2} from './light/SpotLight2'
export {iObjectCommons} from './object/iObjectCommons'
export {iCameraCommons} from './object/iCameraCommons'
export {iLightCommons} from './object/iLightCommons'
export {iGeometryCommons} from './geometry/iGeometryCommons'
export {iMaterialCommons} from './material/iMaterialCommons'
export {upgradeTexture} from './ITexture'
export {upgradeWebGLRenderer, setThreeRendererMode} from './IRenderer'
export {RootScene} from './object/RootScene'
export type {ICameraControls, TControlsCtor, ICameraControlsEventMap} from './camera/ICameraControls'
export type {ICamera, ICameraEventMap, ICameraUserData, TCameraControlsMode, ICameraSetDirtyOptions} from './ICamera'
export type {IGeometry, IGeometryUserData, IGeometryEventMap, IGeometrySetDirtyOptions} from './IGeometry'
export type {IMaterial, IMaterialEventMap, IMaterialParameters, IMaterialUserData, IMaterialSetDirtyOptions, IMaterialTemplate, IMaterialGenerator, AnimateTimeMaterial} from './IMaterial'
export type {IObject3D, IMesh, IObject3DEventMap, ISetDirtyCommonOptions, IObjectSetDirtyOptions, IObjectProcessor, IObject3DUserData, IObjectExtension} from './IObject'
export type {IRenderManager, IRenderManagerOptions, IWebGLRenderer, IRenderManagerEventMap, IAnimationLoopEvent, TThreeRendererMode, TThreeRendererModeUserData, IRenderManagerUpdateEvent, RendererBlitOptions} from './IRenderer'
export type {IScene, ISceneEventMap, ISceneSetDirtyOptions, AddObjectOptions, AddModelOptions, ISceneUserData, IWidget} from './IScene'
export type {ITexture, ITextureUserData, ITextureEventMap} from './ITexture'
export type {ILight} from './light/ILight'
